DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'look') THEN
        CREATE SCHEMA look;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'tr') THEN
        CREATE SCHEMA tr;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'org') THEN
        CREATE SCHEMA org;
    END IF;
END $EF$;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'log') THEN
        CREATE SCHEMA log;
    END IF;
END $EF$;


CREATE TABLE look."AddressType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "AddressType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."Area" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "Area_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" text NULL,
    "LastName" text NULL,
    "PhotoPath" text NULL,
    "IsAdmin" boolean NOT NULL,
    "IsLocked" boolean NOT NULL,
    "CompanyId" integer NOT NULL,
    "LicenseType" text NULL,
    "UserRole" text NULL,
    "CreatedAt" timestamp with time zone NULL,
    "CreatedBy" text NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);


CREATE TABLE org."CompanyDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "PhoneNumber" character varying(13) NULL,
    "LicenseNumber" text NULL,
    "PetitionDate" date NULL,
    "PetitionNumber" character varying(12) NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    "DocPath" text NULL,
    "TIN" double precision NULL,
    CONSTRAINT "CompanyDetails_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."EducationLevel" (
    "ID" smallint NOT NULL DEFAULT (nextval('look.educationlevel_id_seq'::regclass)),
    "Name" character varying(50) NOT NULL,
    "Dari" text NULL,
    parentid smallint NULL,
    "Sorter" character varying(50) NULL,
    CONSTRAINT pk_educationlevel PRIMARY KEY ("ID")
);


CREATE TABLE look."FormsReference" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "FormsReference_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."GuaranteeType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "GuaranteeType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."IdentityCardType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "IdentityCardType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."Location" (
    "ID" integer NOT NULL DEFAULT (nextval('look.location_id_seq'::regclass)),
    "Dari" character varying(255) NOT NULL,
    "IsActive" integer NOT NULL,
    "Code" character(3) NULL,
    "Path" character varying(255) NULL,
    "Path_Dari" character varying(255) NULL,
    "ParentID" integer NULL,
    "TypeID" integer NULL,
    "Name" character varying(255) NULL,
    CONSTRAINT pk_location PRIMARY KEY ("ID")
);


CREATE TABLE look."LostdocumentsType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "LostdocumentsType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE org."PetitionWriterSecurities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RegistrationNumber" character varying(50) NOT NULL,
    "PetitionWriterName" character varying(200) NOT NULL,
    "PetitionWriterFatherName" character varying(200) NOT NULL,
    "LicenseNumber" character varying(50) NOT NULL,
    "PetitionCount" integer NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "BankReceiptNumber" character varying(100) NOT NULL,
    "SerialNumberStart" character varying(100) NOT NULL,
    "SerialNumberEnd" character varying(100) NOT NULL,
    "DistributionDate" date NOT NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "UpdatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "PetitionWriterSecurities_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."PropertyType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "PropertyType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."PUnitType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "PUnitType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE org."SecuritiesDistribution" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RegistrationNumber" character varying(50) NOT NULL,
    "LicenseOwnerName" character varying(200) NOT NULL,
    "LicenseOwnerFatherName" character varying(200) NOT NULL,
    "TransactionGuideName" character varying(200) NOT NULL,
    "LicenseNumber" character varying(50) NOT NULL,
    "DocumentType" integer NULL,
    "PropertySubType" integer NULL,
    "VehicleSubType" integer NULL,
    "PropertySaleCount" integer NULL,
    "PropertySaleSerialStart" character varying(100) NULL,
    "PropertySaleSerialEnd" character varying(100) NULL,
    "BayWafaCount" integer NULL,
    "BayWafaSerialStart" character varying(100) NULL,
    "BayWafaSerialEnd" character varying(100) NULL,
    "RentCount" integer NULL,
    "RentSerialStart" character varying(100) NULL,
    "RentSerialEnd" character varying(100) NULL,
    "VehicleSaleCount" integer NULL,
    "VehicleSaleSerialStart" character varying(100) NULL,
    "VehicleSaleSerialEnd" character varying(100) NULL,
    "VehicleExchangeCount" integer NULL,
    "VehicleExchangeSerialStart" character varying(100) NULL,
    "VehicleExchangeSerialEnd" character varying(100) NULL,
    "RegistrationBookType" integer NULL,
    "RegistrationBookCount" integer NULL,
    "DuplicateBookCount" integer NULL,
    "PricePerDocument" numeric(18,2) NULL,
    "TotalDocumentsPrice" numeric(18,2) NULL,
    "RegistrationBookPrice" numeric(18,2) NULL,
    "TotalSecuritiesPrice" numeric(18,2) NULL,
    "BankReceiptNumber" character varying(100) NULL,
    "DeliveryDate" date NULL,
    "DistributionDate" date NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "UpdatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "SecuritiesDistribution_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE org."Seta" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionTypeId" integer NULL,
    "InquiryNumber" integer NULL,
    "InquiryDate" date NULL,
    "SetaSerialNumber" integer NULL,
    "SetaStampedDate" date NULL,
    "CompanyId" integer NULL,
    "DocPath" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "Seta_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE look."TransactionType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "TransactionType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE "User" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Address" text NOT NULL,
    "ImgPath" text NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);


CREATE TABLE look."ViolationType" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Des" text NULL,
    CONSTRAINT "ViolationType_pkey" PRIMARY KEY ("Id")
);


CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);


CREATE TABLE org."CompanyAccountInfo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "SettlementInfo" character varying(500) NULL,
    "TaxPaymentAmount" numeric(18,2) NOT NULL,
    "SettlementYear" integer NULL,
    "TaxPaymentDate" date NULL,
    "TransactionCount" integer NULL,
    "CompanyCommission" numeric(18,2) NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "CompanyAccountInfo_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyAccountInfo_CompanyDetails" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE org."CompanyCancellationInfo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "LicenseCancellationLetterNumber" character varying(100) NULL,
    "RevenueCancellationLetterNumber" character varying(100) NULL,
    "LicenseCancellationLetterDate" date NULL,
    "Remarks" character varying(1000) NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "CompanyCancellationInfo_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CompanyCancellationInfo_CompanyDetails" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE log.companydetailsaudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "PropertyName" text NULL,
    CONSTRAINT companydetailsaudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "companydetailsaudit_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id")
);


CREATE TABLE org."Haqulemtyaz" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FormNumber" integer NULL,
    "FormDate" date NULL,
    "SubmissionFormNumber" integer NULL,
    "SubmissionFormDate" date NULL,
    "CompanyId" integer NULL,
    "DocPath" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "Haqulemtyaz_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Haqulemtyaz_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id")
);


CREATE TABLE org."LicenseDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LicenseNumber" double precision NOT NULL,
    "IssueDate" date NULL,
    "ExpireDate" date NULL,
    "AreaId" integer NULL,
    "OfficeAddress" text NULL,
    "CompanyId" integer NULL,
    "DocPath" text NULL,
    "LicenseType" text NULL,
    "LicenseCategory" text NULL,
    "RoyaltyAmount" numeric NULL,
    "RoyaltyDate" date NULL,
    "PenaltyAmount" numeric NULL,
    "PenaltyDate" date NULL,
    "HrLetter" text NULL,
    "HrLetterDate" date NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "LicenseDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "LicenseDetails_AreaId_fkey" FOREIGN KEY ("AreaId") REFERENCES look."Area" ("Id"),
    CONSTRAINT "LicenseDetails_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id")
);


CREATE TABLE org."PeriodicForm" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReferenceId" integer NULL,
    "FormNumber" integer NULL,
    "FormDate" date NULL,
    "SubmissionDate" date NULL,
    "MaktobNumber" text NULL,
    "MaktobDate" date NULL,
    "DiagnosisNumber" integer NULL,
    "Details" text NULL,
    "DocPath" text NULL,
    "CompanyId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "PeriodicForm_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PeriodicForm_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id"),
    CONSTRAINT "PeriodicForm_ReferenceId_fkey" FOREIGN KEY ("ReferenceId") REFERENCES look."FormsReference" ("Id")
);


CREATE TABLE org."Gaurantee" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GuaranteeTypeId" integer NULL,
    "PropertyDocumentNumber" bigint NULL,
    "PropertyDocumentDate" date NULL,
    "SenderMaktobNumber" text NULL,
    "SenderMaktobDate" date NULL,
    "AnswerdMaktobNumber" bigint NULL,
    "AnswerdMaktobDate" date NULL,
    "DateofGuarantee" date NULL,
    "GuaranteeDocNumber" bigint NULL,
    "GuaranteeDate" date NULL,
    "CompanyId" integer NULL,
    "DocPath" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "Gaurantee_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Gaurantee_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id"),
    CONSTRAINT "Gaurantee_GuaranteeTypeId_fkey" FOREIGN KEY ("GuaranteeTypeId") REFERENCES look."GuaranteeType" ("Id")
);


CREATE TABLE org."CompanyOwner" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "GrandFatherName" text NULL,
    "EducationLevelId" smallint NULL,
    "DateofBirth" date NULL,
    "IdentityCardTypeId" integer NULL,
    "IndentityCardNumber" double precision NULL,
    "Jild" text NULL,
    "Safha" text NULL,
    "CompanyId" integer NULL,
    "SabtNumber" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    "PothoPath" text NULL,
    "PhoneNumber" text NULL,
    "WhatsAppNumber" text NULL,
    "OwnerProvinceId" integer NULL,
    "OwnerDistrictId" integer NULL,
    "OwnerVillage" text NULL,
    "PermanentProvinceId" integer NULL,
    "PermanentDistrictId" integer NULL,
    "PermanentVillage" text NULL,
    "TemporaryProvinceId" integer NULL,
    "TemporaryDistrictId" integer NULL,
    "TemporaryVillage" text NULL,
    CONSTRAINT "CompanyOwner_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "CompanyOwner_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id"),
    CONSTRAINT "CompanyOwner_EducationLevelId_fkey" FOREIGN KEY ("EducationLevelId") REFERENCES look."EducationLevel" ("ID"),
    CONSTRAINT "CompanyOwner_IdentityCardTypeId_fkey" FOREIGN KEY ("IdentityCardTypeId") REFERENCES look."IdentityCardType" ("Id"),
    CONSTRAINT "CompanyOwner_OwnerDistrictId_fkey" FOREIGN KEY ("OwnerDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwner_OwnerProvinceId_fkey" FOREIGN KEY ("OwnerProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwner_PermanentDistrictId_fkey" FOREIGN KEY ("PermanentDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwner_PermanentProvinceId_fkey" FOREIGN KEY ("PermanentProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwner_TemporaryDistrictId_fkey" FOREIGN KEY ("TemporaryDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwner_TemporaryProvinceId_fkey" FOREIGN KEY ("TemporaryProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE org."Guarantors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "GrandFatherName" text NULL,
    "IdentityCardTypeId" integer NULL,
    "CompanyId" integer NULL,
    "IndentityCardNumber" double precision NULL,
    "Jild" integer NULL,
    "Safha" integer NULL,
    "SabtNumber" integer NULL,
    "PhoneNumber" character varying(13) NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    "PothoPath" text NULL,
    "PaddressProvinceId" integer NULL,
    "PaddressDistrictId" integer NULL,
    "PaddressVillage" text NULL,
    "TaddressProvinceId" integer NULL,
    "TaddressDistrictId" integer NULL,
    "TaddressVillage" text NULL,
    "GuaranteeTypeId" integer NULL,
    "PropertyDocumentNumber" bigint NULL,
    "PropertyDocumentDate" date NULL,
    "SenderMaktobNumber" text NULL,
    "SenderMaktobDate" date NULL,
    "AnswerdMaktobNumber" bigint NULL,
    "AnswerdMaktobDate" date NULL,
    "DateofGuarantee" date NULL,
    "GuaranteeDocNumber" bigint NULL,
    "GuaranteeDate" date NULL,
    "GuaranteeDocPath" text NULL,
    "CourtName" character varying(255) NULL,
    "CollateralNumber" character varying(100) NULL,
    "SetSerialNumber" character varying(100) NULL,
    "GuaranteeDistrictId" integer NULL,
    "BankName" character varying(255) NULL,
    "DepositNumber" character varying(100) NULL,
    "DepositDate" date NULL,
    CONSTRAINT "Guarantors_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Guarantors_CompanyId_fkey" FOREIGN KEY ("CompanyId") REFERENCES org."CompanyDetails" ("Id"),
    CONSTRAINT "Guarantors_GuaranteeDistrictId_fkey" FOREIGN KEY ("GuaranteeDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "Guarantors_GuaranteeTypeId_fkey" FOREIGN KEY ("GuaranteeTypeId") REFERENCES look."GuaranteeType" ("Id"),
    CONSTRAINT "Guarantors_IdentityCardTypeId_fkey" FOREIGN KEY ("IdentityCardTypeId") REFERENCES look."IdentityCardType" ("Id"),
    CONSTRAINT "Guarantors_PaddressDistrictId_fkey" FOREIGN KEY ("PaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "Guarantors_PaddressProvinceId_fkey" FOREIGN KEY ("PaddressProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "Guarantors_TaddressDistrictId_fkey" FOREIGN KEY ("TaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "Guarantors_TaddressProvinceId_fkey" FOREIGN KEY ("TaddressProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE tr."PropertyDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PNumber" integer NOT NULL,
    "PArea" integer NOT NULL,
    "PUnitTypeId" integer NULL,
    "NumofFloor" integer NULL,
    "NumofRooms" integer NULL,
    "PropertyTypeId" integer NULL,
    "CustomPropertyType" text NULL,
    "Price" double precision NULL,
    "PriceText" text NULL,
    "RoyaltyAmount" double precision NULL,
    "TransactionTypeId" integer NULL,
    "Status" text NOT NULL,
    "VerifiedBy" text NULL,
    "VerifiedAt" timestamp with time zone NULL,
    "ApprovedBy" text NULL,
    "ApprovedAt" timestamp with time zone NULL,
    "Des" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "FilePath" text NULL,
    "PreviousDocumentsPath" text NULL,
    "ExistingDocumentsPath" text NULL,
    iscomplete boolean NULL DEFAULT (false),
    iseditable boolean NULL DEFAULT (false),
    west text NULL,
    south text NULL,
    east text NULL,
    north text NULL,
    "DocumentType" text NULL,
    "IssuanceNumber" text NULL,
    "IssuanceDate" timestamp with time zone NULL,
    "SerialNumber" text NULL,
    "TransactionDate" timestamp with time zone NULL,
    CONSTRAINT "PropertyDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyDetails_PUnitTypeId_fkey" FOREIGN KEY ("PUnitTypeId") REFERENCES look."PUnitType" ("Id"),
    CONSTRAINT "PropertyDetails_PropertyTypeId_fkey" FOREIGN KEY ("PropertyTypeId") REFERENCES look."PropertyType" ("Id"),
    CONSTRAINT "PropertyDetails_TransactionTypeId_fkey" FOREIGN KEY ("TransactionTypeId") REFERENCES look."TransactionType" ("Id")
);


CREATE TABLE tr."VehiclesPropertyDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PermitNo" integer NOT NULL,
    "PilateNo" integer NOT NULL,
    "TypeOfVehicle" text NULL,
    "Model" text NULL,
    "EnginNo" integer NULL,
    "ShasiNo" integer NULL,
    "Color" text NULL,
    "Price" double precision NULL,
    "PriceText" text NULL,
    "RoyaltyAmount" double precision NULL,
    "PropertyTypeId" integer NULL,
    "TransactionTypeId" integer NULL,
    "Des" text NULL,
    "FilePath" text NULL,
    "VehicleHand" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    iscomplete boolean NULL,
    iseditable boolean NULL,
    CONSTRAINT "VehiclesPropertyDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "VehiclesPropertyDetails_PropertyTypeId_fkey" FOREIGN KEY ("PropertyTypeId") REFERENCES look."PropertyType" ("Id"),
    CONSTRAINT "VehiclesPropertyDetails_TransactionTypeId_fkey" FOREIGN KEY ("TransactionTypeId") REFERENCES look."TransactionType" ("Id")
);


CREATE TABLE org."Violation" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ViolationTypeId" integer NOT NULL,
    "ViolationDate" date NULL,
    "NotifyDate" date NULL,
    "NumberOfViolation" integer NULL,
    "DateOfsummons" date NULL,
    "PresentedDate" date NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "Violation_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Violation_ViolationTypeId_fkey" FOREIGN KEY ("ViolationTypeId") REFERENCES look."ViolationType" ("Id")
);


CREATE TABLE log.licenseaudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LicenseId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "PropertyName" text NULL,
    CONSTRAINT licenseaudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "licenseaudit_LicenseId_fkey" FOREIGN KEY ("LicenseId") REFERENCES org."LicenseDetails" ("Id")
);


CREATE TABLE log.graunteeaudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GauranteeId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "PropertyName" text NULL,
    CONSTRAINT graunteeaudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "graunteeaudit_GauranteeId_fkey" FOREIGN KEY ("GauranteeId") REFERENCES org."Gaurantee" ("Id")
);


CREATE TABLE org."CompanyOwnerAddress" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "AddressTypeId" integer NULL,
    "ProvinceId" integer NULL,
    "DistrictId" integer NULL,
    "CompanyOwnerId" integer NULL,
    "Village" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "Status" boolean NULL,
    CONSTRAINT "CompanyOwnerAddress_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "CompanyOwnerAddress_AddressTypeId_fkey" FOREIGN KEY ("AddressTypeId") REFERENCES look."AddressType" ("Id"),
    CONSTRAINT "CompanyOwnerAddress_CompanyOwnerId_fkey" FOREIGN KEY ("CompanyOwnerId") REFERENCES org."CompanyOwner" ("Id"),
    CONSTRAINT "CompanyOwnerAddress_DistrictId_fkey" FOREIGN KEY ("DistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwnerAddress_ProvinceId_fkey" FOREIGN KEY ("ProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE org."CompanyOwnerAddressHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyOwnerId" integer NOT NULL,
    "ProvinceId" integer NULL,
    "DistrictId" integer NULL,
    "Village" text NULL,
    "AddressType" character varying(20) NOT NULL,
    "EffectiveFrom" timestamp without time zone NOT NULL,
    "EffectiveTo" timestamp without time zone NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "CompanyOwnerAddressHistory_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "CompanyOwnerAddressHistory_CompanyOwnerId_fkey" FOREIGN KEY ("CompanyOwnerId") REFERENCES org."CompanyOwner" ("Id") ON DELETE CASCADE,
    CONSTRAINT "CompanyOwnerAddressHistory_DistrictId_fkey" FOREIGN KEY ("DistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "CompanyOwnerAddressHistory_ProvinceId_fkey" FOREIGN KEY ("ProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE log.companyowneraudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OwnerId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "PropertyName" text NULL,
    CONSTRAINT companyowneraudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "companyowneraudit_OwnerId_fkey" FOREIGN KEY ("OwnerId") REFERENCES org."CompanyOwner" ("Id")
);


CREATE TABLE log.guarantorsaudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GuarantorsId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "PropertyName" text NULL,
    CONSTRAINT guarantorsaudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "guarantorsaudit_GuarantorsId_fkey" FOREIGN KEY ("GuarantorsId") REFERENCES org."Guarantors" ("Id")
);


CREATE TABLE tr."BuyerDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "GrandFather" text NOT NULL,
    "IndentityCardNumber" double precision NULL,
    "TazkiraType" text NULL,
    "TazkiraVolume" text NULL,
    "TazkiraPage" text NULL,
    "TazkiraNumber" text NULL,
    "PhoneNumber" character varying(14) NULL,
    "PaddressProvinceId" integer NULL,
    "PaddressDistrictId" integer NULL,
    "PaddressVillage" text NULL,
    "TaddressProvinceId" integer NULL,
    "TaddressDistrictId" integer NULL,
    "TaddressVillage" text NULL,
    "PropertyDetailsId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    photo text NULL,
    "NationalIdCard" text NULL,
    "RoleType" text NULL,
    "AuthorizationLetter" text NULL,
    "TaxIdentificationNumber" text NULL,
    "AdditionalDetails" text NULL,
    "SharePercentage" double precision NULL,
    "ShareAmount" double precision NULL,
    "Price" double precision NULL,
    "PriceText" text NULL,
    "RoyaltyAmount" double precision NULL,
    "HalfPrice" double precision NULL,
    "TransactionType" text NULL,
    "TransactionTypeDescription" text NULL,
    "RentStartDate" timestamp with time zone NULL,
    "RentEndDate" timestamp with time zone NULL,
    CONSTRAINT "BuyerDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "BuyerDetails_PaddressDistrictId_fkey" FOREIGN KEY ("PaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "BuyerDetails_PaddressProvinceId_fkey" FOREIGN KEY ("PaddressProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "BuyerDetails_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id"),
    CONSTRAINT "BuyerDetails_TaddressDistrictId_fkey" FOREIGN KEY ("TaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "BuyerDetails_TaddressProvinceId_fkey" FOREIGN KEY ("TaddressProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE tr."PropertyAddress" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProvinceId" integer NULL,
    "DistrictId" integer NULL,
    "PropertyDetailsId" integer NULL,
    "Village" text NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "PropertyAddress_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyAddress_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id")
);


CREATE TABLE log.propertyaudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "PropertyName" text NULL,
    CONSTRAINT propertyaudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "propertyaudit_PropertyId_fkey" FOREIGN KEY ("PropertyId") REFERENCES tr."PropertyDetails" ("Id")
);


CREATE TABLE tr."PropertyCancellations" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyDetailsId" integer NOT NULL,
    "CancellationDate" timestamp without time zone NOT NULL,
    "CancellationReason" text NULL,
    "CancelledBy" character varying(50) NULL,
    "Status" character varying(50) NOT NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PropertyCancellations_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyCancellations_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE tr."PropertyDocument" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyDetailsId" integer NOT NULL,
    "DocumentCategory" text NOT NULL,
    "FilePath" text NOT NULL,
    "OriginalFileName" text NULL,
    "Description" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "PropertyDocument_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyDocument_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE tr."PropertyOwnershipHistory" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyDetailsId" integer NOT NULL,
    "OwnerName" text NOT NULL,
    "OwnerFatherName" text NULL,
    "OwnershipStartDate" timestamp without time zone NULL,
    "OwnershipEndDate" timestamp without time zone NULL,
    "TransferDocumentPath" text NULL,
    "Notes" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "PropertyOwnershipHistory_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyOwnershipHistory_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE tr."PropertyPayment" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyDetailsId" integer NOT NULL,
    "PaymentDate" timestamp without time zone NOT NULL,
    "AmountPaid" double precision NOT NULL,
    "PaymentMethod" text NULL,
    "ReceiptNumber" text NULL,
    "BalanceRemaining" double precision NULL,
    "Notes" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "PropertyPayment_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyPayment_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE tr."PropertyValuation" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyDetailsId" integer NOT NULL,
    "ValuationDate" timestamp without time zone NOT NULL,
    "ValuationAmount" double precision NOT NULL,
    "ValuatorName" text NULL,
    "ValuatorOrganization" text NULL,
    "ValuationDocumentPath" text NULL,
    "Notes" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "PropertyValuation_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyValuation_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id") ON DELETE CASCADE
);


CREATE TABLE tr."SellerDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "GrandFather" text NOT NULL,
    "IndentityCardNumber" double precision NULL,
    "TazkiraType" text NULL,
    "TazkiraVolume" text NULL,
    "TazkiraPage" text NULL,
    "TazkiraNumber" text NULL,
    "PhoneNumber" character varying(14) NULL,
    "PaddressProvinceId" integer NULL,
    "PaddressDistrictId" integer NULL,
    "PaddressVillage" text NULL,
    "TaddressProvinceId" integer NULL,
    "TaddressDistrictId" integer NULL,
    "TaddressVillage" text NULL,
    "PropertyDetailsId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    photo text NULL,
    "NationalIdCard" text NULL,
    "RoleType" text NULL,
    "AuthorizationLetter" text NULL,
    "HeirsLetter" text NULL,
    "TaxIdentificationNumber" text NULL,
    "AdditionalDetails" text NULL,
    "SharePercentage" double precision NULL,
    "ShareAmount" double precision NULL,
    CONSTRAINT "SellerDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "SellerDetails_PaddressDistrictId_fkey" FOREIGN KEY ("PaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "SellerDetails_PaddressProvinceId_fkey" FOREIGN KEY ("PaddressProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "SellerDetails_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id"),
    CONSTRAINT "SellerDetails_TaddressDistrictId_fkey" FOREIGN KEY ("TaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "SellerDetails_TaddressProvinceId_fkey" FOREIGN KEY ("TaddressProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE tr."WitnessDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "IndentityCardNumber" double precision NULL,
    "TazkiraType" text NULL,
    "TazkiraVolume" text NULL,
    "TazkiraPage" text NULL,
    "TazkiraNumber" text NULL,
    "PhoneNumber" character varying(14) NULL,
    "PropertyDetailsId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "NationalIdCard" text NULL,
    "PaddressProvinceId" integer NULL,
    "PaddressDistrictId" integer NULL,
    "PaddressVillage" text NULL,
    "RelationshipToParties" text NULL,
    "WitnessType" text NULL,
    CONSTRAINT "WitnessDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "WitnessDetails_PaddressDistrictId_fkey" FOREIGN KEY ("PaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "WitnessDetails_PaddressProvinceId_fkey" FOREIGN KEY ("PaddressProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "WitnessDetails_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."PropertyDetails" ("Id")
);


CREATE TABLE log.vehicleaudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "ColumnName" text NULL,
    CONSTRAINT vehicleaudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "vehicleaudit_VehicleId_fkey" FOREIGN KEY ("VehicleId") REFERENCES tr."VehiclesPropertyDetails" ("Id")
);


CREATE TABLE tr."VehiclesBuyerDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "GrandFather" text NOT NULL,
    "IndentityCardNumber" double precision NULL,
    "TazkiraType" text NULL,
    "TazkiraVolume" text NULL,
    "TazkiraPage" text NULL,
    "TazkiraNumber" text NULL,
    "PhoneNumber" character varying(14) NULL,
    "PaddressProvinceId" integer NULL,
    "PaddressDistrictId" integer NULL,
    "PaddressVillage" text NULL,
    "TaddressProvinceId" integer NULL,
    "TaddressDistrictId" integer NULL,
    "TaddressVillage" text NULL,
    "PropertyDetailsId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    photo text NULL,
    "NationalIdCardPath" text NULL,
    "RoleType" text NULL,
    "AuthorizationLetter" text NULL,
    "RentStartDate" timestamp with time zone NULL,
    "RentEndDate" timestamp with time zone NULL,
    CONSTRAINT "VehiclesBuyerDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "VehiclesBuyerDetails_PaddressDistrictId_fkey" FOREIGN KEY ("PaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "VehiclesBuyerDetails_PaddressProvinceId_fkey" FOREIGN KEY ("PaddressProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "VehiclesBuyerDetails_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."VehiclesPropertyDetails" ("Id"),
    CONSTRAINT "VehiclesBuyerDetails_TaddressDistrictId_fkey" FOREIGN KEY ("TaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "VehiclesBuyerDetails_TaddressProvinceId_fkey" FOREIGN KEY ("TaddressProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE tr."VehiclesSellerDetails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "GrandFather" text NOT NULL,
    "IndentityCardNumber" double precision NULL,
    "TazkiraType" text NULL,
    "TazkiraVolume" text NULL,
    "TazkiraPage" text NULL,
    "TazkiraNumber" text NULL,
    "PhoneNumber" character varying(14) NULL,
    "PaddressProvinceId" integer NULL,
    "PaddressDistrictId" integer NULL,
    "PaddressVillage" text NULL,
    "TaddressProvinceId" integer NULL,
    "TaddressDistrictId" integer NULL,
    "TaddressVillage" text NULL,
    "PropertyDetailsId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    photo text NULL,
    "NationalIdCardPath" text NULL,
    "RoleType" text NULL,
    "AuthorizationLetter" text NULL,
    "HeirsLetter" text NULL,
    CONSTRAINT "VehiclesSellerDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "VehiclesSellerDetails_PaddressDistrictId_fkey" FOREIGN KEY ("PaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "VehiclesSellerDetails_PaddressProvinceId_fkey" FOREIGN KEY ("PaddressProvinceId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "VehiclesSellerDetails_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."VehiclesPropertyDetails" ("Id"),
    CONSTRAINT "VehiclesSellerDetails_TaddressDistrictId_fkey" FOREIGN KEY ("TaddressDistrictId") REFERENCES look."Location" ("ID"),
    CONSTRAINT "VehiclesSellerDetails_TaddressProvinceId_fkey" FOREIGN KEY ("TaddressProvinceId") REFERENCES look."Location" ("ID")
);


CREATE TABLE tr."VehiclesWitnessDetails" (
    "Id" integer NOT NULL DEFAULT (nextval('tr."WitnessDetails_Id_seq"'::regclass)),
    "FirstName" text NOT NULL,
    "FatherName" text NOT NULL,
    "IndentityCardNumber" double precision NULL,
    "TazkiraType" text NULL,
    "TazkiraVolume" text NULL,
    "TazkiraPage" text NULL,
    "TazkiraNumber" text NULL,
    "PhoneNumber" character varying(14) NULL,
    "PropertyDetailsId" integer NULL,
    "CreatedAt" timestamp without time zone NULL,
    "CreatedBy" character varying(50) NULL,
    "NationalIdCard" text NULL,
    CONSTRAINT "VehiclesWitnessDetails_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "VehiclesWitnessDetails_PropertyDetailsId_fkey" FOREIGN KEY ("PropertyDetailsId") REFERENCES tr."VehiclesPropertyDetails" ("Id")
);


CREATE TABLE log.propertybuyeraudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BuyerId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "ColumnName" text NULL,
    CONSTRAINT propertybuyeraudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "propertybuyeraudit_BuyerId_fkey" FOREIGN KEY ("BuyerId") REFERENCES tr."BuyerDetails" ("Id")
);


CREATE TABLE tr."PropertyCancellationDocuments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "PropertyCancellationId" integer NOT NULL,
    "FilePath" text NOT NULL,
    "OriginalFileName" text NULL,
    "CreatedAt" timestamp without time zone NOT NULL,
    "CreatedBy" character varying(50) NULL,
    CONSTRAINT "PropertyCancellationDocuments_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "PropertyCancellationDocuments_PropertyCancellationId_fkey" FOREIGN KEY ("PropertyCancellationId") REFERENCES tr."PropertyCancellations" ("Id") ON DELETE CASCADE
);


CREATE TABLE log.propertyselleraudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SellerId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "ColumnName" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    CONSTRAINT propertyselleraudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "propertyselleraudit_SellerId_fkey" FOREIGN KEY ("SellerId") REFERENCES tr."SellerDetails" ("Id")
);


CREATE TABLE log.vehiclebuyeraudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleBuyerId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "ColumnName" text NULL,
    CONSTRAINT vehiclebuyeraudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "vehiclebuyeraudit_VehicleBuyerId_fkey" FOREIGN KEY ("VehicleBuyerId") REFERENCES tr."VehiclesBuyerDetails" ("Id")
);


CREATE TABLE log.vehicleselleraudit (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VehicleSellerId" integer NOT NULL,
    "OldValue" text NULL,
    "NewValue" text NULL,
    "UpdatedBy" text NULL,
    "UpdatedAt" timestamp without time zone NULL,
    "ColumnName" text NULL,
    CONSTRAINT vehicleselleraudit_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "vehicleselleraudit_VehicleSellerId_fkey" FOREIGN KEY ("VehicleSellerId") REFERENCES tr."VehiclesSellerDetails" ("Id")
);


CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");


CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");


CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");


CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");


CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");


CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");


CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");


CREATE INDEX "IX_BuyerDetails_PaddressDistrictId" ON tr."BuyerDetails" ("PaddressDistrictId");


CREATE INDEX "IX_BuyerDetails_PaddressProvinceId" ON tr."BuyerDetails" ("PaddressProvinceId");


CREATE INDEX "IX_BuyerDetails_PropertyDetailsId" ON tr."BuyerDetails" ("PropertyDetailsId");


CREATE INDEX "IX_BuyerDetails_TaddressDistrictId" ON tr."BuyerDetails" ("TaddressDistrictId");


CREATE INDEX "IX_BuyerDetails_TaddressProvinceId" ON tr."BuyerDetails" ("TaddressProvinceId");


CREATE INDEX "IX_CompanyAccountInfo_CompanyId" ON org."CompanyAccountInfo" ("CompanyId");


CREATE INDEX "IX_CompanyCancellationInfo_CompanyId" ON org."CompanyCancellationInfo" ("CompanyId");


CREATE INDEX "IX_companydetailsaudit_CompanyId" ON log.companydetailsaudit ("CompanyId");


CREATE INDEX "IX_CompanyOwner_CompanyId" ON org."CompanyOwner" ("CompanyId");


CREATE INDEX "IX_CompanyOwner_EducationLevelId" ON org."CompanyOwner" ("EducationLevelId");


CREATE INDEX "IX_CompanyOwner_IdentityCardTypeId" ON org."CompanyOwner" ("IdentityCardTypeId");


CREATE INDEX "IX_CompanyOwner_OwnerDistrictId" ON org."CompanyOwner" ("OwnerDistrictId");


CREATE INDEX "IX_CompanyOwner_OwnerProvinceId" ON org."CompanyOwner" ("OwnerProvinceId");


CREATE INDEX "IX_CompanyOwner_PermanentDistrictId" ON org."CompanyOwner" ("PermanentDistrictId");


CREATE INDEX "IX_CompanyOwner_PermanentProvinceId" ON org."CompanyOwner" ("PermanentProvinceId");


CREATE INDEX "IX_CompanyOwner_TemporaryDistrictId" ON org."CompanyOwner" ("TemporaryDistrictId");


CREATE INDEX "IX_CompanyOwner_TemporaryProvinceId" ON org."CompanyOwner" ("TemporaryProvinceId");


CREATE INDEX "IX_CompanyOwnerAddress_AddressTypeId" ON org."CompanyOwnerAddress" ("AddressTypeId");


CREATE INDEX "IX_CompanyOwnerAddress_CompanyOwnerId" ON org."CompanyOwnerAddress" ("CompanyOwnerId");


CREATE INDEX "IX_CompanyOwnerAddress_DistrictId" ON org."CompanyOwnerAddress" ("DistrictId");


CREATE INDEX "IX_CompanyOwnerAddress_ProvinceId" ON org."CompanyOwnerAddress" ("ProvinceId");


CREATE INDEX "IX_CompanyOwnerAddressHistory_CompanyOwnerId" ON org."CompanyOwnerAddressHistory" ("CompanyOwnerId");


CREATE INDEX "IX_CompanyOwnerAddressHistory_DistrictId" ON org."CompanyOwnerAddressHistory" ("DistrictId");


CREATE INDEX "IX_CompanyOwnerAddressHistory_ProvinceId" ON org."CompanyOwnerAddressHistory" ("ProvinceId");


CREATE INDEX "IX_companyowneraudit_OwnerId" ON log.companyowneraudit ("OwnerId");


CREATE INDEX "IX_Gaurantee_CompanyId" ON org."Gaurantee" ("CompanyId");


CREATE INDEX "IX_Gaurantee_GuaranteeTypeId" ON org."Gaurantee" ("GuaranteeTypeId");


CREATE INDEX "IX_graunteeaudit_GauranteeId" ON log.graunteeaudit ("GauranteeId");


CREATE INDEX "IX_Guarantors_CompanyId" ON org."Guarantors" ("CompanyId");


CREATE INDEX "IX_Guarantors_GuaranteeDistrictId" ON org."Guarantors" ("GuaranteeDistrictId");


CREATE INDEX "IX_Guarantors_GuaranteeTypeId" ON org."Guarantors" ("GuaranteeTypeId");


CREATE INDEX "IX_Guarantors_IdentityCardTypeId" ON org."Guarantors" ("IdentityCardTypeId");


CREATE INDEX "IX_Guarantors_PaddressDistrictId" ON org."Guarantors" ("PaddressDistrictId");


CREATE INDEX "IX_Guarantors_PaddressProvinceId" ON org."Guarantors" ("PaddressProvinceId");


CREATE INDEX "IX_Guarantors_TaddressDistrictId" ON org."Guarantors" ("TaddressDistrictId");


CREATE INDEX "IX_Guarantors_TaddressProvinceId" ON org."Guarantors" ("TaddressProvinceId");


CREATE INDEX "IX_guarantorsaudit_GuarantorsId" ON log.guarantorsaudit ("GuarantorsId");


CREATE INDEX "IX_Haqulemtyaz_CompanyId" ON org."Haqulemtyaz" ("CompanyId");


CREATE INDEX "IX_licenseaudit_LicenseId" ON log.licenseaudit ("LicenseId");


CREATE INDEX "IX_LicenseDetails_AreaId" ON org."LicenseDetails" ("AreaId");


CREATE INDEX "IX_LicenseDetails_CompanyId" ON org."LicenseDetails" ("CompanyId");


CREATE INDEX "IX_PeriodicForm_CompanyId" ON org."PeriodicForm" ("CompanyId");


CREATE INDEX "IX_PeriodicForm_ReferenceId" ON org."PeriodicForm" ("ReferenceId");


CREATE INDEX "IX_PetitionWriterSecurities_BankReceiptNumber" ON org."PetitionWriterSecurities" ("BankReceiptNumber");


CREATE INDEX "IX_PetitionWriterSecurities_LicenseNumber" ON org."PetitionWriterSecurities" ("LicenseNumber");


CREATE UNIQUE INDEX "IX_PetitionWriterSecurities_RegistrationNumber" ON org."PetitionWriterSecurities" ("RegistrationNumber");


CREATE INDEX "IX_PropertyAddress_PropertyDetailsId" ON tr."PropertyAddress" ("PropertyDetailsId");


CREATE INDEX "IX_propertyaudit_PropertyId" ON log.propertyaudit ("PropertyId");


CREATE INDEX "IX_propertybuyeraudit_BuyerId" ON log.propertybuyeraudit ("BuyerId");


CREATE INDEX "IX_PropertyCancellationDocuments_PropertyCancellationId" ON tr."PropertyCancellationDocuments" ("PropertyCancellationId");


CREATE INDEX "IX_PropertyCancellations_PropertyDetailsId" ON tr."PropertyCancellations" ("PropertyDetailsId");


CREATE INDEX "IX_PropertyDetails_PropertyTypeId" ON tr."PropertyDetails" ("PropertyTypeId");


CREATE INDEX "IX_PropertyDetails_PUnitTypeId" ON tr."PropertyDetails" ("PUnitTypeId");


CREATE INDEX "IX_PropertyDetails_TransactionTypeId" ON tr."PropertyDetails" ("TransactionTypeId");


CREATE INDEX "IX_PropertyDocument_PropertyDetailsId" ON tr."PropertyDocument" ("PropertyDetailsId");


CREATE INDEX "IX_PropertyOwnershipHistory_PropertyDetailsId" ON tr."PropertyOwnershipHistory" ("PropertyDetailsId");


CREATE INDEX "IX_PropertyPayment_PropertyDetailsId" ON tr."PropertyPayment" ("PropertyDetailsId");


CREATE INDEX "IX_propertyselleraudit_SellerId" ON log.propertyselleraudit ("SellerId");


CREATE INDEX "IX_PropertyValuation_PropertyDetailsId" ON tr."PropertyValuation" ("PropertyDetailsId");


CREATE INDEX "IX_SecuritiesDistribution_BankReceiptNumber" ON org."SecuritiesDistribution" ("BankReceiptNumber");


CREATE INDEX "IX_SecuritiesDistribution_LicenseNumber" ON org."SecuritiesDistribution" ("LicenseNumber");


CREATE UNIQUE INDEX "IX_SecuritiesDistribution_RegistrationNumber" ON org."SecuritiesDistribution" ("RegistrationNumber");


CREATE INDEX "IX_SecuritiesDistribution_TransactionGuideName" ON org."SecuritiesDistribution" ("TransactionGuideName");


CREATE INDEX "IX_SellerDetails_PaddressDistrictId" ON tr."SellerDetails" ("PaddressDistrictId");


CREATE INDEX "IX_SellerDetails_PaddressProvinceId" ON tr."SellerDetails" ("PaddressProvinceId");


CREATE INDEX "IX_SellerDetails_PropertyDetailsId" ON tr."SellerDetails" ("PropertyDetailsId");


CREATE INDEX "IX_SellerDetails_TaddressDistrictId" ON tr."SellerDetails" ("TaddressDistrictId");


CREATE INDEX "IX_SellerDetails_TaddressProvinceId" ON tr."SellerDetails" ("TaddressProvinceId");


CREATE INDEX "IX_vehicleaudit_VehicleId" ON log.vehicleaudit ("VehicleId");


CREATE INDEX "IX_vehiclebuyeraudit_VehicleBuyerId" ON log.vehiclebuyeraudit ("VehicleBuyerId");


CREATE INDEX "IX_VehiclesBuyerDetails_PaddressDistrictId" ON tr."VehiclesBuyerDetails" ("PaddressDistrictId");


CREATE INDEX "IX_VehiclesBuyerDetails_PaddressProvinceId" ON tr."VehiclesBuyerDetails" ("PaddressProvinceId");


CREATE INDEX "IX_VehiclesBuyerDetails_PropertyDetailsId" ON tr."VehiclesBuyerDetails" ("PropertyDetailsId");


CREATE INDEX "IX_VehiclesBuyerDetails_TaddressDistrictId" ON tr."VehiclesBuyerDetails" ("TaddressDistrictId");


CREATE INDEX "IX_VehiclesBuyerDetails_TaddressProvinceId" ON tr."VehiclesBuyerDetails" ("TaddressProvinceId");


CREATE INDEX "IX_vehicleselleraudit_VehicleSellerId" ON log.vehicleselleraudit ("VehicleSellerId");


CREATE INDEX "IX_VehiclesPropertyDetails_PropertyTypeId" ON tr."VehiclesPropertyDetails" ("PropertyTypeId");


CREATE INDEX "IX_VehiclesPropertyDetails_TransactionTypeId" ON tr."VehiclesPropertyDetails" ("TransactionTypeId");


CREATE INDEX "IX_VehiclesSellerDetails_PaddressDistrictId" ON tr."VehiclesSellerDetails" ("PaddressDistrictId");


CREATE INDEX "IX_VehiclesSellerDetails_PaddressProvinceId" ON tr."VehiclesSellerDetails" ("PaddressProvinceId");


CREATE INDEX "IX_VehiclesSellerDetails_PropertyDetailsId" ON tr."VehiclesSellerDetails" ("PropertyDetailsId");


CREATE INDEX "IX_VehiclesSellerDetails_TaddressDistrictId" ON tr."VehiclesSellerDetails" ("TaddressDistrictId");


CREATE INDEX "IX_VehiclesSellerDetails_TaddressProvinceId" ON tr."VehiclesSellerDetails" ("TaddressProvinceId");


CREATE INDEX "IX_VehiclesWitnessDetails_PropertyDetailsId" ON tr."VehiclesWitnessDetails" ("PropertyDetailsId");


CREATE INDEX "IX_Violation_ViolationTypeId" ON org."Violation" ("ViolationTypeId");


CREATE INDEX "IX_WitnessDetails_PaddressDistrictId" ON tr."WitnessDetails" ("PaddressDistrictId");


CREATE INDEX "IX_WitnessDetails_PaddressProvinceId" ON tr."WitnessDetails" ("PaddressProvinceId");


CREATE INDEX "IX_WitnessDetails_PropertyDetailsId" ON tr."WitnessDetails" ("PropertyDetailsId");


