-- Seed PetitionWriterActivityLocations from MahalPalyatName.json
-- Table: org."PetitionWriterActivityLocations"
-- Columns: Id (serial), Name, DariName (unique), IsActive, CreatedAt, CreatedBy, UpdatedAt, UpdatedBy

BEGIN;

-- Remove all existing data
DELETE FROM org."PetitionWriterActivityLocations";

-- Reset the serial Id back to 1
ALTER SEQUENCE IF EXISTS org."PetitionWriterActivityLocations_Id_seq" RESTART WITH 1;

INSERT INTO org."PetitionWriterActivityLocations" ("Name", "DariName", "IsActive", "CreatedAt", "CreatedBy")
VALUES
('Adjacent to ستره Court', 'جوار ستره محکمه', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Kabul Justice Rights', 'جوارریاست حقوق کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Kabul Municipality', 'جوارشاروالی کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Education شهر', 'جوارریاست معارف شهر', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of کارکنان Education', 'جوارریاست کارکنان معارف', true, NOW(), 'SYSTEM'),
('Adjacent to Kabul Province', 'جوارولایت کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Kabul Electricity', 'جوارریاست برق کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Criminal Investigations', 'جوارریاست تحقیقات جنایی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Emirate Cases Kabul Province', 'جوارریاست قضایای امارت ولایت کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of عمومی Emirate Cases', 'جوارریاست عمومی قضایای امارت', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Statistics and Information', 'جوارریاست احصایه ومعلومات', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of E-Tazkira Services', 'جوارریاست خدمات تذکره الکترونیکی', true, NOW(), 'SYSTEM'),
('Adjacent to Court Documents District 1', 'جوارمحکمه وثایق حوزه 1', true, NOW(), 'SYSTEM'),
('Adjacent to Court Documents District 2', 'جوارمحکمه وثایق حوزه 2', true, NOW(), 'SYSTEM'),
('Adjacent to Court Documents District 3', 'جوارمحکمه وثایق حوزه 3', true, NOW(), 'SYSTEM'),
('Adjacent to Court Documents District 4', 'جوارمحکمه وثایق حوزه 4', true, NOW(), 'SYSTEM'),
('Adjacent to Court Documents District 5', 'جوارمحکمه وثایق حوزه 5', true, NOW(), 'SYSTEM'),
('Adjacent to Court Documents District 6', 'جوارمحکمه وثایق حوزه 6', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Medical Council', 'جوارریاست شورای طبی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Central Registration', 'جوارریاست ثبت مرکزی', true, NOW(), 'SYSTEM'),
('Adjacent to Court Urban District 1', 'جوارمحکمه شهری حوزه 1', true, NOW(), 'SYSTEM'),
('Adjacent to Court Urban District 2', 'جوارمحکمه شهری حوزه 2', true, NOW(), 'SYSTEM'),
('Adjacent to Court Urban District 3', 'جوارمحکمه شهری حوزه 3', true, NOW(), 'SYSTEM'),
('Adjacent to Court Urban District 4', 'جوارمحکمه شهری حوزه 4', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Passport', 'جوارریاست پاسپورت', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Education Kabul Province', 'جوارریاست معارف ولایت کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Traffic', 'جوارریاست ترافیک', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Transport Regulation', 'جوارریاست تنظیم ترانسپورت', true, NOW(), 'SYSTEM'),
('Adjacent to معینیت Counter Narcotics Deputy', 'جوارمعینیت مبارزه بامواد مخدر', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Kabul Electricity', 'جوارریاست برق کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Results and Certificates', 'جوار ریاست نتایج وشهادت نامه ها', true, NOW(), 'SYSTEM'),
('Adjacent to Kabul Police Command', 'جوار قوماندانی امنیه کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Water Supply', 'جوارریاست آبرسانی', true, NOW(), 'SYSTEM'),
('Adjacent to Statistics and Information سایت برچی', 'جوار احصایه ومعلومات سایت برچی', true, NOW(), 'SYSTEM'),
('Adjacent to Kabul Customs', 'جوار گمرک کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Afghan Announcements', 'جوار افغان اعلانات', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Complaints Hearing of Vice and Virtue', 'جوارریاست سمع شکایات امربالمعروف', true, NOW(), 'SYSTEM'),
('Adjacent to Court Military', 'جوار محکمه نظامی', true, NOW(), 'SYSTEM'),
('Adjacent to معینیت Food and Medicine', 'جوار معینیت غذا وادویه', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Returnee Migrants Affairs', 'جوارریاست امورمهاجرین عودت کننده گان', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Animal Health', 'جوار ریاست صحت حیوانی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Kabul Public Health', 'جوار ریاست صحت عامه کابل', true, NOW(), 'SYSTEM'),
('Adjacent to معینیت Land and Properties', 'جوار معینیت زمین داری واراضی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Pension Treasury', 'جوار ریاست خزینه تقاعد', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Private Education', 'جوار ریاست تعلیمات خصوصی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Religious Specializations', 'جوار ریاست تخصصات دینی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Water Supply زون کابل', 'جوار ریاست آبرسانی زون کابل', true, NOW(), 'SYSTEM'),
('Adjacent to معینیت خدمات Urban Municipality', 'جوارمعینیت خدمات شهری شاروالی', true, NOW(), 'SYSTEM'),
('Statistics and Information سایت جاده میوند', 'احصایه ومعلومات سایت جاده میوند', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of سرسبزی Municipality', 'جوارریاست سرسبزی شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Statistics and Information سایت مکرویان', 'جواراحصایه ومعلومات سایت مکرویان', true, NOW(), 'SYSTEM'),
('Adjacent to شفاخانه ابن سینا', 'جوار شفاخانه ابن سینا', true, NOW(), 'SYSTEM'),
('Adjacent to انستیتوت انرژی وآب', 'جوار انستیتوت انرژی وآب', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی سروبی', 'جوار ولسوالی سروبی', true, NOW(), 'SYSTEM'),
('Adjacent to Statistics and Information سایت برچی', 'جواراحصایه ومعلومات سایت برچی', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی گلدره', 'جوارولسوالی گلدره', true, NOW(), 'SYSTEM'),
('Adjacent to اداره عمومی Statistics and Information', 'جواراداره عمومی احصایه ومعلومات', true, NOW(), 'SYSTEM'),
('Adjacent to لوی ریااست نظارت وتعقیب فرامین واحکام', 'جوارلوی ریااست نظارت وتعقیب فرامین واحکام', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of امورشرکت های امارتی', 'جوارریاست امورشرکت های امارتی', true, NOW(), 'SYSTEM'),
('Adjacent to اداره تنظیم امورزندان ها', 'جوار اداره تنظیم امورزندان ها', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of عمومی شرکت های امارتی', 'جوارریاست عمومی شرکت های امارتی', true, NOW(), 'SYSTEM'),
('Adjacent to اداره تعلیمات تحنیکی ومسلکی', 'جواراداره تعلیمات تحنیکی ومسلکی', true, NOW(), 'SYSTEM'),
('Adjacent to اکادمی علوم', 'جواراکادمی علوم', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of عمومی رادیوتلویزیون', 'جوارریاست عمومی رادیوتلویزیون', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 1 امنیتی', 'جوارآمریت حوزه 1 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 2 امنیتی', 'جوارآمریت حوزه 2 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 3 امنیتی', 'جوارآمریت حوزه 3 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 4 امنیتی', 'جوارآمریت حوزه 4 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 5 امنیتی', 'جوارآمریت حوزه 5 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 6 امنیتی', 'جوارآمریت حوزه 6 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 7 امنیتی', 'جوارآمریت حوزه 7 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 8 امنیتی', 'جوارآمریت حوزه 8 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 9 امنیتی', 'جوارآمریت حوزه 9 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 10 امنیتی', 'جوارآمریت حوزه 10 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 11 امنیتی', 'جوارآمریت حوزه 11 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 12 امنیتی', 'جوارآمریت حوزه 12 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 13 امنیتی', 'جوارآمریت حوزه 13 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 14 امنیتی', 'جوارآمریت حوزه 14 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 15 امنیتی', 'جوارآمریت حوزه 15 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 16 امنیتی', 'جوارآمریت حوزه 16 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 17 امنیتی', 'جوارآمریت حوزه 17 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 18 امنیتی', 'جوارآمریت حوزه 18 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 19 امنیتی', 'جوارآمریت حوزه 19 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 20 امنیتی', 'جوارآمریت حوزه 20 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 21 امنیتی', 'جوارآمریت حوزه 21 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to آمریت District 22 امنیتی', 'جوارآمریت حوزه 22 امنیتی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 1 Municipality', 'جوارریاست ناحیه 1 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 2 Municipality', 'جوارریاست ناحیه 2 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 3 Municipality', 'جوارریاست ناحیه 3 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 4 Municipality', 'جوارریاست ناحیه 4 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 5 Municipality', 'جوارریاست ناحیه 5 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 6 Municipality', 'جوارریاست ناحیه 6 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 7 Municipality', 'جوارریاست ناحیه 7 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 8 Municipality', 'جوارریاست ناحیه 8 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 8 Municipality', 'جوارریاست ناحیه 8 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 10 Municipality', 'جوارریاست ناحیه 10 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 11 Municipality', 'جوارریاست ناحیه 11 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 12 Municipality', 'جوارریاست ناحیه 12 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 13 Municipality', 'جوارریاست ناحیه 13 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 14 Municipality', 'جوارریاست ناحیه 14 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 15 Municipality', 'جوارریاست ناحیه 15 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 16 Municipality', 'جوارریاست ناحیه 16 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 17 Municipality', 'جوارریاست ناحیه 17 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 18 Municipality', 'جوارریاست ناحیه 18 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 19 Municipality', 'جوارریاست ناحیه 19 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 20 Municipality', 'جوارریاست ناحیه 20 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 21 Municipality', 'جوارریاست ناحیه 21 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ناحیه 22 Municipality', 'جوارریاست ناحیه 22 شاروالی', true, NOW(), 'SYSTEM'),
('Adjacent to Court استناف Kabul Province', 'جوار محکمه استناف ولایت کابل', true, NOW(), 'SYSTEM'),
('Adjacent to پوسته خانه ناحیه 8', 'جوار پوسته خانه ناحیه 8', true, NOW(), 'SYSTEM'),
('Adjacent to پوهنتون کابل', 'جوارپوهنتون کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of عمومی المپیک', 'جوارریاست عمومی المپیک', true, NOW(), 'SYSTEM'),
('Adjacent to مدیریت Traffic کابل', 'جوارمدیریت ترافیک کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Education ولایت کابل', 'جوارریاست معارف ولایت  کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Statistics and Information', 'جوارریاست احصایه ومعلومات', true, NOW(), 'SYSTEM'),
('Adjacent to Statistics and Information سایت دارالامان', 'جواراحصایه ومعلومات سایت دارالامان', true, NOW(), 'SYSTEM'),
('Adjacent to احصایه ومعلوامات سایت جاده میوند', 'جواراحصایه ومعلوامات سایت جاده میوند', true, NOW(), 'SYSTEM'),
('Adjacent to Court استناف کابل', 'جوارمحکمه استناف کابل', true, NOW(), 'SYSTEM'),
('Adjacent to District 1 تعلیمی', 'جوار حوزه 1 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 2 تعلیمی', 'جوارحوزه 2 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 3 تعلیمی', 'جوارحوزه 3 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 4 تعلیمی', 'جوارحوزه 4 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 5 تعلیمی', 'جوارحوزه 5 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 6 تعلیمی', 'جوارحوزه 6 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 7 تعلیمی', 'جوارحوزه 7 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 8 تعلیمی', 'جوارحوزه 8 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 9 تعلیمی', 'جوارحوزه 9 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 10 تعلیمی', 'جوارحوزه 10 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 11 تعلیمی', 'جوارحوزه 11 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 12 تعلیمی', 'جوارحوزه 12 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 13 تعلیمی', 'جوارحوزه 13 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 14 تعلیمی', 'جوارحوزه 14 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 15 تعلیمی', 'جوارحوزه 15 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 16 تعلیمی', 'جوارحوزه 16 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 17 تعلیمی', 'جوارحوزه 17 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 18 تعلیمی', 'جوارحوزه 18 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 19 تعلیمی', 'جوارحوزه 19 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 20 تعلیمی', 'جوارحوزه 20 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 21 تعلیمی', 'جوارحوزه 21 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to District 22 تعلیمی', 'جوارحوزه 22 تعلیمی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of قوای بشری', 'جوارریاست قوای بشری', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی پغمان', 'جوار ولسوالی پغمان', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی سروبی', 'جوار ولسوالی سروبی', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی موسهی', 'جوار ولسوالی موسهی', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی بگرامی', 'جوار ولسوالی بگرامی', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی قره باغ', 'جوارولسوالی قره باغ', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی چهارآسیاب', 'جوارولسوالی چهارآسیاب', true, NOW(), 'SYSTEM'),
('Adjacent to والسوالی میربچه کوت', 'جواروالسوالی میربچه کوت', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی شکردره', 'جوارولسوالی شکردره', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی استالف', 'جوارولسوالی استالف', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی ده سبز', 'جوارولسوالی ده سبز', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی کلکان', 'جوار ولسوالی کلکان', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی خاکجبار', 'جوارولسوالی خاکجبار', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی فرزه', 'جوارولسوالی فرزه', true, NOW(), 'SYSTEM'),
('Adjacent to ولسوالی گلدره', 'جوارولسوالی گلدره', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of تعلیمات اسلامی', 'جوارریاست تعلیمات اسلامی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of Religious Specializations', 'جوارریاست تخصصات دینی', true, NOW(), 'SYSTEM'),
('Adjacent to معینیت Urban Kabul Municipality', 'جوارمعینیت شهری شاروالی کابل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of سره میاشت', 'جوارریاست سره میاشت', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of افغانتور', 'جوارریاست افغانتور', true, NOW(), 'SYSTEM'),
('Adjacent to یاست امورمهاجرین وعودت کننده گان', 'جواریاست امورمهاجرین وعودت کننده گان', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of امور شهداومعلولین', 'جوارریاست امور شهداومعلولین', true, NOW(), 'SYSTEM'),
('Adjacent to شفاخانه آغوش 5000 بستر', 'جوارشفاخانه آغوش 5000 بستر', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of برشنا', 'جوارریاست برشنا', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of ارشاد،حج اوقاف', 'جوارریاست ارشاد،حج اوقاف', true, NOW(), 'SYSTEM'),
('Adjacent to انستیتوت انرژی وآب', 'جوارانستیتوت انرژی وآب', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of عمومی اداره امور', 'جوارریاست عمومی اداره امور', true, NOW(), 'SYSTEM'),
('Adjacent to اداره عمومی امتحانات', 'جواراداره عمومی امتحانات', true, NOW(), 'SYSTEM'),
('Adjacent to اداره عمومی حفاظت محیط زیست', 'جواراداره عمومی حفاظت محیط زیست', true, NOW(), 'SYSTEM'),
('Adjacent to اداره آماده گی مبارزه باحوادث', 'جواراداره آماده گی مبارزه باحوادث', true, NOW(), 'SYSTEM'),
('Adjacent to اداره معیاروکیفیت', 'جواراداره معیاروکیفیت', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت معادن وپطرولیم', 'جواروزارت معادن وپطرولیم', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت مالیه', 'جواروزارت مالیه', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت Education', 'جواروزارت معارف', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت صحت عامه', 'جواروزارت صحت عامه', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت امورشهدا ومعلولین', 'جواروزارت امورشهدا ومعلولین', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت عدلیه', 'جوار وزارت عدلیه', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت امورداخله', 'جواروزارت امورداخله', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت زراعت آبیاری ومالداری', 'جواروزارت زراعت آبیاری ومالداری', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت امورخارجه', 'جواروزارت امورخارجه', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت فواید عامه', 'جواروزارت فواید عامه', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت شهرسازی ومسکن', 'جواروزارت شهرسازی ومسکن', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت مخابرات وتکنالوژی معلوماتی', 'جوار وزارت مخابرات وتکنالوژی معلوماتی', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت دفاع', 'جواروزارت دفاع', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت ارشاد،حج اوقاف', 'جواروزارت ارشاد،حج اوقاف', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت صنعت وتجارت', 'جواروزارت صنعت وتجارت', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت اقتصاد', 'جواروزارت اقتصاد', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت احیاءوانکشاف دهات', 'جواروزارت احیاءوانکشاف دهات', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت انرژی وآب', 'جواروزارت انرژی وآب', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت امربالمعروف،نهی عن المنکر', 'جواروزارت امربالمعروف،نهی عن المنکر', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت کارواموراجتماعی', 'جواروزارت کارواموراجتماعی', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت ترانسپورت وهوانوردی', 'جواروزارت ترانسپورت وهوانوردی', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت امورمهاجرین وعودت کننده گان', 'جواروزارت امورمهاجرین وعودت کننده گان', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت اطلاعات وفرهنک', 'جواروزارت اطلاعات وفرهنک', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت امور اراضی واستردادزمین های غصب شده امارتی', 'جواروزارت امور اراضی واستردادزمین های غصب شده امارتی', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت تحصیلات عالی', 'جواروزارت تحصیلات عالی', true, NOW(), 'SYSTEM'),
('Adjacent to وزارت سرحدات،اقوام وقبایل', 'جواروزارت سرحدات،اقوام وقبایل', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of مساعدت های حقوقی', 'جوارریاست مساعدت های حقوقی', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of نتایج وشهات نامه ها', 'جوارریاست نتایج وشهات نامه ها', true, NOW(), 'SYSTEM'),
('Adjacent to Directorate of تدریسات ثانوی', 'جوارریاست تدریسات ثانوی', true, NOW(), 'SYSTEM')
ON CONFLICT ("DariName") DO NOTHING;

COMMIT;
