// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPIBackend.Configuration;

#nullable disable

namespace WebAPIBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210100000_AddRoleTypeAndDocumentFields")]
    partial class AddRoleTypeAndDocumentFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Note: This is a simplified designer file. The actual model snapshot is maintained
            // by Entity Framework Core and will be updated automatically when migrations are applied.
            // This file serves as a reference for the migration that adds RoleType, AuthorizationLetter, 
            // and HeirsLetter fields to SellerDetails and VehiclesSellerDetails tables.
#pragma warning restore 612, 618
        }
    }
}
