// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPIBackend.Configuration;

#nullable disable

namespace WebAPIBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211_AddDeedDateToPropertyDetails")]
    partial class AddDeedDateToPropertyDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebAPIBackend.sModels.PropertyDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DeedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Des")
                        .HasColumnType("text");

                    b.Property<string>("Doctype")
                        .HasColumnType("text");

                    b.Property<string>("East")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool?>("Iscomplete")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Iseditable")
                        .HasColumnType("boolean");

                    b.Property<int?>("NumofFloor")
                        .HasColumnType("integer");

                    b.Property<int?>("NumofRooms")
                        .HasColumnType("integer");

                    b.Property<int>("Parea")
                        .HasColumnType("integer");

                    b.Property<int?>("PropertyTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Pnumber")
                        .HasColumnType("integer");

                    b.Property<int?>("PunitTypeId")
                        .HasColumnType("integer");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("PriceText")
                        .HasColumnType("text");

                    b.Property<double?>("RoyaltyAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("South")
                        .HasColumnType("text");

                    b.Property<int?>("TransactionTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("West")
                        .HasColumnType("text");

                    b.Property<string>("North")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PropertyDetails", "tr");
                });

#pragma warning restore 612, 618
        }
    }
}
