// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPIBackend.Configuration;

#nullable disable

namespace WebAPIBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207081500_AddPropertyFieldsToBuyerAndSellerDetails")]
    partial class AddPropertyFieldsToBuyerAndSellerDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This is a partial migration class that adds new columns to existing tables
            // The full model snapshot is maintained in AppDbContextModelSnapshot.cs
            // This migration adds: PropertyTypeId, Price, PriceText, RoyaltyAmount, HalfPrice
            // to BuyerDetails, SellerDetails, VehiclesBuyerDetails, and VehiclesSellerDetails tables
#pragma warning restore 612, 618
        }
    }
}
