using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WebAPIBackend.Configuration;

#nullable disable

namespace WebAPIBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227093000_AddPropertyCancellationDocuments")]
    public partial class AddPropertyCancellationDocuments : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'tr'
                        AND table_name = 'PropertyCancellationDocuments'
                    ) THEN
                        CREATE TABLE tr.""PropertyCancellationDocuments"" (
                            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                            ""PropertyCancellationId"" integer NOT NULL,
                            ""FilePath"" text NOT NULL,
                            ""OriginalFileName"" text NULL,
                            ""CreatedAt"" timestamp without time zone NOT NULL,
                            ""CreatedBy"" character varying(50) NULL,
                            CONSTRAINT ""PropertyCancellationDocuments_pkey"" PRIMARY KEY (""Id""),
                            CONSTRAINT ""PropertyCancellationDocuments_PropertyCancellationId_fkey"" FOREIGN KEY (""PropertyCancellationId"")
                                REFERENCES tr.""PropertyCancellations"" (""Id"")
                        );

                        CREATE INDEX ""IX_PropertyCancellationDocuments_PropertyCancellationId""
                            ON tr.""PropertyCancellationDocuments"" (""PropertyCancellationId"");
                    END IF;
                END $$;
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = 'tr'
                        AND table_name = 'PropertyCancellationDocuments'
                    ) THEN
                        DROP TABLE tr.""PropertyCancellationDocuments"";
                    END IF;
                END $$;
            ");
        }
    }
}
