// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WebAPIBackend.Configuration;

#nullable disable

namespace WebAPIBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260102100000_AddTinColumnToCompanyDetailsFixed")]
    partial class AddTinColumnToCompanyDetailsFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is intentionally left minimal as we're using raw SQL
            // The actual model snapshot is maintained in AppDbContextModelSnapshot.cs
        }
    }
}
